### ISSUE TITLE
Missing E-Mail for free licences 

### ISSUE THREAD

**Issue by Denon9205** [nucleonautomation/Gluonix-Designer#1]
First of all, thank you very much for your excellent tool. I would like to use your tool for a small project. In your detailed videos (thanks for those as well), you mentioned that one can contact you by email for a free license. Unfortunately, I can’t find the email address anywhere.

**Comment by nucleonautomation** [comment]
Thank you for reaching out and for your kind words about our tool! We're glad to hear that you find it useful.

You don’t need to worry about requesting a license via email. As soon as you run the software, it will automatically activate with a Pro license. We’ve added the license for safekeeping, but our goal is to keep the software free for everyone.

If you encounter any issues or have suggestions for future updates, please feel free to let us know. We're always here to help!
